name: Fetch Data and Notify Parent

on: 
  push:
  workflow_dispatch:

jobs:
  
  notify-parent:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Puppeteer script
        run: node fetchData.js
        env:
          JSTOR_USER: ${{ secrets.JSTOR_USER }}
          JSTOR_PASSWORD: ${{ secrets.JSTOR_PASSWORD }}
          JSTOR_PROJECT: ${{ secrets.JSTOR_PROJECT }}

      - name: Commit and push new data
        run: |
          git config --global user.name 'Your Name'
          git config --global user.email 'your-username@users.noreply.github.com'
          git add -f jstor.xls vocabulary.xls
          git commit -am "Update JSTOR data"
          git push

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PARENT_REPO_TOKEN }}
          repository: imaginerio/imaginerio-etl
          event-type: submodule-update